name: 'Terraform'
on:
  push:
    branches:  [ devcontainer ]
 

env:
  TF_IN_AUTOMATION: true
  TF_WORKSPACE: -dev
  TF_BACKEND_PATH: dev.tfvars
  TF_VAR_tf_backend_bucket_name: terraform-vpc-state
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
          with:
           aws-region: "US East"

      - uses: actions/checkout@v1
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.2

      - name: Terraform Init
        id: init 
        run: terraform init
          
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
              
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false 
        continue-on-error: true
